### ISSUE TITLE
audio api를 사용하여 주파수 데이터 추출하기

### ISSUE THREAD

**Issue by fairesy** [fairesy/hear-color#11]
☆★☆★드림☆★☆★
[input] 추출하고 싶은 주파수 영역 : 베이스면 낮은 주파수 같은 식으로 음색 등을 구분해낼 수 있다.
[output] input에 해당하는 data array

알아야하는 것 : audio api, fft, array 데이터 안꼬이게 잘 처리하기.

**Comment by fairesy** [comment]
https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&ved=0CE4QFjAHahUKEwipn-mWwqPHAhXnH6YKHQLXB2A&url=http%3A%2F%2Fsti.or.kr%2Fjboard%2Fdownload.php%3Ffile_name%3D%25C0%25BD%25C7%25E2%25C3%25F8%25C1%25A42.PDF%26file_size%3D1381044%26code%3Dboard2&ei=PDjLVamRI-e_mAWCrp-ABg&usg=AFQjCNGQ3GS2O8gRVcV2O065_xU1HbETNA&sig2=zgY7sJZzfn9g5TcbHEOl-A&bvm=bv.99804247,d.dGY

**Comment by fairesy** [comment]
http://blog.daum.net/belife9/9699359

**Comment by fairesy** [comment]
http://www.hanbit.co.kr/network/view.html?bi_id=420

**Comment by fairesy** [comment]
fft 관련글 모음 링크 http://hbesthee.tistory.com/1388

**Comment by fairesy** [comment]
web audio api free online book
http://chimera.labs.oreilly.com/books/1234000001552/index.html

**Comment by fairesy** [comment]
https://www.new-bamboo.co.uk/blog/2011/10/26/experiments-with-the-html5-audio-data-api/

**Comment by fairesy** [comment]
fft 라이브러리!!!!
https://github.com/corbanbrook/dsp.js
쓸 수 있는 건지 살펴봐야겠다.

**Comment by fairesy** [comment]
**
http://www.smartjava.org/content/exploring-html5-web-audio-visualizing-sound

**Comment by fairesy** [comment]
mozilla wiki. api가 아예 다른가...........?
https://wiki.mozilla.org/Audio_Data_API#Complete_Example:_Visualizing_Audio_Spectrum

**Comment by zeakd** [comment]
오 열심히 쓴다

**Comment by fairesy** [comment]
흡족한 질문제목
http://stackoverflow.com/questions/14789283/what-does-the-fft-data-in-the-web-audio-api-correspond-to

**Comment by fairesy** [comment]
읽기 싫게 생겼지만 유용하게 생긴 듯
http://www.cs.tut.fi/sgn/arg/intro/basics.html

http://www.billposer.org/Linguistics/Computation/LectureNotes/AudioData.html

**Comment by fairesy** [comment]
오류없이 돌아가는 오디오 코드 샘플 오랜만.....
http://www.flightarcade.com/learn/webaudio

**Comment by fairesy** [comment]
http://www.keithmcmillen.com/blog/making-music-in-the-browser-web-audio-api-part-1/
http://www.willvillanueva.com/the-web-audio-api-from-nodeexpress-to-your-browser/

audio visaulization section
http://joshondesign.com/p/books/canvasdeepdive/chapter12.html

**Comment by fairesy** [comment]
링크 걸어둔 것들에서 필요한 부분들은 읽어봐야 하지만, 일단은 audioHelper.js에 createBarVisualizer(from, to) 로 원하는 주파수 대역의 데이터를 활용한 그래프 그리기 완료.
