### ISSUE TITLE
audio - color 매칭 시킬 규칙 만들기

### ISSUE THREAD

**Issue by fairesy** [fairesy/hear-color#14]

**Comment by fairesy** [comment]
![Imgur](http://i.imgur.com/tKsq2xn.jpg)
![Imgur](http://i.imgur.com/jBCBMYd.png)

#### 피크점에 해당하는 색상(hue)을 매치시킨다.(dominant hue)

-가장 낮은 일정 주파수 대역과 가장 높은 주파수 일정 대역은 매칭 데이터에서 제외시킨다.

#### barHeight에 따라 채도/명도를 추가적으로 부여한다.

-크면(db값이 높으면) 채도/명도를 높게, 작으면 낮게.

##### 고민거리
- 전체 frequency data 그래프의 모양으로 대강의 분류가 가능한데, 전체 그래프의 모양도 활용할 수 있는 방안을 고민해본다. 
- tempo를 구할 수 있는 방법이 있을까?

**Comment by fairesy** [comment]
[TO교수님]
hear-color/log.js에 간단간단히나마 정리되지 않은 로그를 쓰고 있어요!

**Comment by fairesy** [comment]
색 : https://github.com/fairesy/hear-color/wiki/emotion-color
음향 : https://github.com/fairesy/hear-color/wiki/frequency_spectrum
계속 추가&쓸 수 있는 형태로 추려서 정리

**Comment by yongwoo2** [comment]
@fairesy 그래 보고 있다.
