### ISSUE TITLE
음악 전체의 frequencyData 구하기

### ISSUE THREAD

**Issue by fairesy** [fairesy/hear-color#15]
frequency data를 누적시켜서 음악 전체의 frequency 그래프가 어떤 모양인지 음악별로 본다.

**Comment by fairesy** [comment]
![뷰렛](http://i.imgur.com/je8hLZ2.png)

**Comment by fairesy** [comment]
뷰렛 - 나는 외로움 그대는 그리움
![뷰렛](http://i.imgur.com/je8hLZ2.png)

센과 치히로의 행방불명 OST(Piano ver.)
![센과치히로](http://i.imgur.com/VFU8udZ.png?1)

아이유-마음
![아이유](http://i.imgur.com/rOJmA0z.png?1)

 어반자카파-River
![River](http://i.imgur.com/upgMFoA.png)

f(x) - electric shock
![일렉트릭쇼크](http://i.imgur.com/WeryNHW.png)

**Comment by fairesy** [comment]
5479aa3f6d7a9f3d1ccc11ec4463f1d610d58ee9

**Comment by yongwoo2** [comment]
잘하고 있네
