### ISSUE TITLE
2주차 리뷰

### ISSUE THREAD

**Issue by yongwoo2** [fairesy/hear-color#19]
https://github.com/fairesy/hear-color/blob/master/hear-color/log.js#L18
- 이건 이미 context에 Source을 연결해서 그런것 같아. 그래서 source가 없을 때만 로직을 실행하다록 하면 될거다.

`canplaythrough`와 `canplay`의 차이는 뭔지 아니?

**Comment by yongwoo2** [comment]
내가 보기엔 잘하고 있다.
사실 backbone.js나 angluar.js보다는 신영이가 하고 싶은 모습에는 지금 하는게 더 좋을 것 같아.

**Comment by yongwoo2** [comment]
그리고 API디자인에 관한건 내가 한번 전체적으로 리뷰해줄께.

**Comment by fairesy** [comment]
앗 네 그 문제는 일단 해결했었어요! context에 연결된 소스가 이미 있어서 그런 것 같아서 물어봐서 고친게 연결하는 부분을 init부분으로 옮겼습니다. source가 없을 때만 로직을 실행하도록은...소스가 없으면 연결할 것이 없는 게 아닌가요....??@_@ 

canplaythrough는 오디오의 전체를 다(어느부분이든) 재생할 수 있는 상태일 때, 
canplay는 일단 재생이 가능할 때, 
로 알고 있습니다

**Comment by yongwoo2** [comment]
@fairesy 
둘 다 맞다.
잘했어.
